# Generated by Django 4.1.4 on 2023-01-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csos', '0002_auto_20230110_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cso',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_updated'),
        ),
        migrations.AlterField(
            model_name='cso',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='date_updated'),
        ),
    ]
